import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'sl';

interface LangContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        balance: 'Balance',
        income: 'Income',
        expense: 'Expense',
        cash: 'Cash',
        card: 'Card',
        add: 'Add',
        cancel: 'Cancel',
        addTransaction: 'Add Transaction',
        method: 'Method',
        amount: 'Amount',
        category: 'Category',
        type: 'Type',
        salary: 'Salary',
        donation: 'Donation',
        other: 'Other',
        transactionHistory: 'Transaction History',
        close: 'Close',
        settings: 'Settings',
        language: 'Language',
        currency: 'Currency',
        erase: 'Erase All Transactions',
        privacy: 'Privacy Policy',
        terms: 'Terms of Use',
        userNotLoggedIn: "User not logged in",
        transactionAdded: "Transaction added!",
        errorSaving: "Error saving.",
        choose: "Choose",
        source: "Source",
        scholarship: "Scholarship",
        groceries: "Groceries",
        home: "Home",
        "eating out": "Eating Out",
        "food delivery": "Food Delivery",
        coffee: "Coffee",
        car: "Car",
        health: "Health",
        sport: "Sport",
        subscriptions: "Subscriptions",
        tech: "Tech",
        entertainment: "Entertainment",
        personal: "Personal",
        clothing: "Clothing",
        gifts: "Gifts",
        education: "Education",
        business: "Business",
        charity: "Charity",
        pets: "Pets",
        confirmErase: "Are you sure?",
        eraseSuccess: "All transactions erased.",
        yes: "Yes",
        ok: "OK",
        export: 'Export',
        exportCSV: 'Export CSV',
        exportPDF: 'Export PDF',
        importCSV: 'Import CSV (Current Month)',
        data: 'Data',
        settingsTitle: 'Settings',
        noUser: 'No user logged in',
        importSuccess: 'Import completed ',
        exportSuccess: 'Export completed ',
        confirm: 'Confirm',
        date: 'Date',
        description: 'Description',
        tour_account_toggle: '👥 Switch between "My View" (just your data) and "Shared View" (includes transactions from users you’ve connected with).',
        tour_balance_section: '💰 This is your total available balance, split between Cash and Card.',
        tour_advice_button: '🤖 Need help saving money? Ask our smart assistant for personalized advice!',
        tour_fab: '☰ Tap here to access settings (⚙️), choose a month (📅), or quickly add a new transaction (+).',
        budgetOverrunTitle: 'Budget Overrun:',
        dismissClick: 'Click anywhere to dismiss',
        totalBalance: 'Total Balance',
        spendingOverview: 'Spending Overview',
        expensesByCategory: 'Expenses by Category',
        viewReports: 'View Full Spending Report',
        latestTransactions: 'Latest transactions',
        seeAll: 'See all',
        today: 'Today',
        yesterday: 'Yesterday',
        sharedUser: 'Shared User',
        assistantMessage: 'Hey! I am here to help!',
        "about.andonijaIntro": "I'm Andonija 👋",
        "about.intro1": "I’m studying Information and Data Technologies at FERI Maribor, where I’ve been learning how to build useful, secure, and user-friendly web sites.",
        "about.intro2": "Spendly started as a school project — now it's a platform that encourages mindful money habits. With clean visuals, easy manual entry, and optional AI features, Spendly helps you stay intentional with every expense.",

        "about.missionTitle": "Our mission",
        "about.mission1": "Spendly is your personal finance companion designed to make budgeting simple, collaborative, and actually enjoyable.",
        "about.mission2": "In a world where most budgeting apps bury core features behind subscriptions, bank logins, or bloated interfaces, Spendly takes a different path.",
        "about.mission3": "Whether you're managing your own money, budgeting as a couple, or saving toward something big, Spendly adapts to your life — not the other way around.",

        "about.banner": "🎉 It’s FREE! No subscriptions. No limits. Just Spendly helping you stay in control of your money — because we care. 💛",

        "about.whySpendly": "Why Spendly",
        "about.value1Title": "Simplicity",
        "about.value1Text": "Manual tracking, no complexity.",
        "about.value2Title": "Privacy",
        "about.value2Text": "No bank connections, full control.",
        "about.value3Title": "Transparency",
        "about.value3Text": "Built by a student, for everyone.",
        "about.value4Title": "Clarity",
        "about.value4Text": "Clean graphs and visuals that make sense.",
        "about.value5Title": "Free",
        "about.value5Text": "No more extra money on subscriptions!",

        "about.ctaTitle": "Join the Movement",
        "about.ctaText": "Spendly gives you everything you need to master your budget —",
        "about.ctaStrong": "completely free",
        "about.ctaButton": "Create Your Free Account",
        "account.myAccount": "My Account",
        "account.personalDetails": "Personal Details",
        "account.fullName": "Full Name",
        "account.profilePhoto": "Profile Photo",
        "account.twofaTitle": "Two-Factor Authentication",
        "account.twofaEnabled": "✅ 2FA is enabled on your account.",
        "account.phonePlaceholder": "Phone Number (e.g. +386...)",
        "account.sendCode": "Send Code",
        "account.enterCode": "Enter Code",
        "account.verifyEnable": "Verify & Enable",
        "account.collaborateTitle": "Collaborate",
        "account.collabDescription": "Want to track finances with a partner, friend, or family member? Enter their email address below to invite them. Once they accept, you'll both see the same budget and transactions — in real-time.",
        "account.emailPlaceholder": "e.g. partner@email.com",
        "account.deleteAccount": "Delete My Account",
        spendSmarter: "Spend Smarter with Spendly!",
        discoverFeatures: "Discover features that help you take full control of your personal finances.",
        funFact: "Fun Fact",
        didYouKnow: "Did you know?",
        statFact: "People who track expenses save up to",
        statMonth: "more each month!",
        saveSmarter: "Ready to save smarter?",
        createAccount: "Create an Account",
        contactTitle: "Contact Us",
        contactIntro1: "Have a question? A bug to report?",
        contactIntro2: "We’d love to hear from you. Just leave us a message below!",
        contactNamePlaceholder: "Your name",
        contactEmailPlaceholder: "Your email",
        contactMessagePlaceholder: "What’s on your mind?",
        sendMessage: "Send Message",
        contactSuccess: "Your message has been sent! We’ll get back to you soon.",
        contactError: "Oops! Something went wrong. Please try again later.",
        contactThanks: "Thanks for taking the time to connect with us. Your feedback helps make Spendly better!",
        heroTitle: "The smarter way to manage money",
        heroSubtitle: "Spendly helps you track every expense...",
        getStarted: "Get started",
        greeting: "Hi",
        greetingMessage: "Hope you're having a good day! ☀️",
        videoNotSupported: "Your browser does not support the video tag.",
        privacyPolicyTitle: "Privacy Policy",
        lastUpdated: "Last updated: May 26, 2025",
        privacyIntro: "At",
        privacyIntroCont: ", your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your personal data.",
        section1Title: "1. Information We Collect",
        infoEmailName: "Email and name during registration",
        infoPhone: "Optional phone number for 2FA",
        infoFinancialData: "Financial data you enter (transactions, budgets)",
        infoBrowserData: "Browser/device info for app improvement",
        section2Title: "2. How We Use Your Information",
        usePersonalizedFeatures: "To provide personalized finance features",
        use2FA: "To protect your account via 2FA",
        useAnalytics: "To analyze usage and improve user experience",
        section3Title: "3. Data Security",
        dataSecurity: "We use Firebase Authentication and Firestore with encrypted connections. Your data is never shared with third parties without consent.",
        section4Title: "4. Your Rights",
        yourRights: "You may request to view, modify, or delete your data at any time by contacting us.",
        section5Title: "5. Changes",
        changesNotice: "This policy may change. Users will be notified of any significant updates.",
        reportsTitle: '📊 Financial Reports',
        filterBy: 'Filter by:',
        filterAll: 'All time',
        filterDay: 'Day',
        filterWeek: 'Week',
        filterMonth: 'Month',
        filterYear: 'Year',
        filterRange: 'Custom range',
        selectYear: 'Select Year',
        chartDailyLabel: 'Daily Expenses (€)',
        chartDailyTitle: 'Daily Spending Trends (€)',
        chartXAxisDate: 'Date',
        chartYAxisAmount: 'Amount',
        chartBarTitle: 'Monthly Incomes vs Expenses (€)',
        chartIncome: 'Income',
        chartExpense: 'Expenses',
        chartXAxisMonth: 'Month',
        chartPieTitle: 'Expenses by Category',
        noCategoryData: 'No expense categories available.',
        chartDoughnutTitle: 'Spending: Card vs Cash',
        onlyOneMethod: 'Only one payment method used in this filter.',
        chartBalanceLabel: 'Balance (€)',
        chartBalanceTitle: 'Your Account Balance Over Time',
        chartYAxisBalance: 'Balance (€)',
        tooltipDate: 'Date',
        tooltipBalance: 'Balance',
        termsTitle: 'Terms of Service',
        termsEffectiveDate: 'Effective Date',
        termsAcceptance: '1. Acceptance of Terms',
        termsAcceptanceText: 'By using Spendly, you agree to be bound by these Terms of Service. If you do not agree, please discontinue use of the application.',
        termsUse: '2. Use of the Service',
        termsUseText: 'Spendly is a personal finance tracking app intended for individuals over the age of 16. You agree not to misuse the service or access data belonging to others.',
        termsSecurity: '3. Account & Security',
        termsSecurityText: 'You are responsible for keeping your login credentials safe. Enabling two-factor authentication (2FA) is recommended for added security.',
        termsPrivacy: '4. Data and Privacy',
        termsPrivacyText: 'Your financial data is stored securely in a Firebase cloud database. We do not sell or share your data with third parties.',
        termsLimitations: '5. Limitations',
        termsLimitationsText: 'Spendly does not connect to bank APIs or provide accounting, tax, or legal advice. All data must be entered manually.',
        termsAI: '6. AI Insights',
        termsAIText: 'Any AI-generated suggestions are informational only and do not constitute financial advice.',
        termsTermination: '7. Termination',
        termsTerminationText: 'We reserve the right to suspend or terminate any account that violates these terms.',
        termsChanges: '8. Changes',
        termsChangesText: 'These Terms may change from time to time. Continued use of the app constitutes acceptance of the updated terms.',
        termsContact: '9. Contact',
        termsContactText: 'If you have questions, contact us at: andonija.todorova@student.um.si',
        sharedBy: 'Shared by',
        anotherUser: 'Another user',

        "direction": "Transfer direction",
        "cardToCash": "Card → Cash",
        "cashToCard": "Cash → Card",

        "invalidAmount": "🚨 Please enter a valid amount greater than 0.",
        "notEnoughCash": "🚨 Balance too low! Not enough cash.",
        "notEnoughCard": "🚨 Balance too low! Not enough card balance.",
        "transferNotEnoughCash": "🚨 Cannot transfer. Not enough cash balance.",
        "transferNotEnoughCard": "🚨 Cannot transfer. Not enough card balance.",
        "resetPassword": "Reset Password",
        "yourEmail": "Your email",
        "sendResetLink": "Send Reset Link",
        "resetLinkSent": "Reset link sent. Check your inbox.",
        "resetFailed": "Failed to send reset email.",
        "emailSent": "Email sent. Check your inbox.",
        "backToLogin": "Back to login",
        "login": "Log In",
        "password": "Password",
        "email": "Email",
        "loggingIn": "Logging in…",
        "or": "or",
        "continueGoogle": "Continue with Google",
        "forgotPassword": "Forgot password?",
        "reset": "Reset",
        "noAccount": "Don’t have an account?",
        "signUp": "Sign up",
        "enterCode": "Enter SMS code",
        "verify": "Verify Code",
        "emailNotVerified": "Email not verified. Please check your inbox.",
        "emailNotVerifiedGoogle": "Google account is not verified. Please verify your email.",
        "smsFailed": "Failed to send SMS verification code.",
        "networkIssue": "Network issue. Retrying...",
        "errorWrongPassword": "Incorrect email or password.",
        "errorUserNotFound": "No account found with this email.",
        "errorTooManyRequests": "Too many attempts. Try again later.",
        "errorInvalidEmail": "Invalid email format.",
        "errorInternal": "An internal error occurred. Please try again.",
        "errorLoginFailed": "Login failed. Please check your credentials.",
        "popupBlocked": "Popup blocked. Switching to redirect login...",
        "errorAccountExists": "Account already exists with this email using another login method.",
        "errorGoogleInvalid": "Invalid Google credentials. Try again.",
        "errorGoogleGeneric": "Google sign-in failed. Please try again.",
        "verificationSuccess": "Verification successful.",
        "smsInvalid": "Invalid code. Please try again.",
        "hi": "Hi",
        "there": "there",
        "niceToMeet": "Nice to meet you!",
        "homePageTitle": "Home",
        "whyJoinSpendly": "Why Join Spendly?",
        "overviewAtGlance": "Dashboard at a glance",
        "overviewText": "Instantly see your financial health with clear, beautiful visuals.",
        "smartBudgetTracking": "Smart Budget Tracking",
        "budgetText": "Never overspend again with intuitive budget tracking.",
        "categorizeExpenses": "Categorize Expenses",
        "categorizeText": "Sort your spending into categories with ease.",
        "detailedAnalytics": "Detailed Analytics",
        "analyticsText": "Understand your spending habits with insightful analytics.",
        "fullHistory": "Full Transaction History",
        "historyText": "Your entire spending history, beautifully displayed.",
        "multiDevice": "Multi-Device Support",
        "multiDeviceText": "Keep your budget in sync across all devices effortlessly.",

        "fact1": "People who track expenses save up to 20% more each month!",
        "fact2": "Budgeting helps reduce impulse purchases by 25%.",
        "fact3": "Couples who share budgets argue 30% less about money.",
        "fact4": "Checking your budget weekly improves savings consistency.",
        "fact5": "Spending awareness boosts financial confidence in 2 weeks.",
        "fact6": "Tracking cash flow can reveal hidden subscriptions.",
        "fact7": "Budgeters are 2x more likely to reach savings goals.",
        "fact8": "Young adults using budget apps save 15% more yearly.",
        "fact9": "Most overspending happens in the last 5 days of the month.",
        "fact10": "Visual graphs boost budget retention by 70%.",
        "account.currentlySharing": "You are currently sharing with",
        "account.stopCollaborating": "Stop Collaborating",
        "fullName": "Full Name",
        "termsConfirm": "I have read and accepted the ",
        "termsOfService": "Terms of Service",
        "and": "and",
        "privacyPolicy": "Privacy Policy",
        "continueWithGoogle": "Continue with Google",
        "alreadyHaveAccount": "Already have an account?",
        "signIn": "Sign in",
        "acceptTerms": "Please accept the terms and privacy policy.",
        "verificationSent": "Verification email sent. Please check your inbox.",
        "emailInUse": "An account with this email already exists.",
        "invalidEmail": "Invalid email address.",
        "weakPassword": "Password must be at least 6 characters.",
        "signupFailed": "Something went wrong. Please try again.",
        "googleSignupFailed": "Google sign-up failed.",
        "noIncomeYet": "🚫 Add income before adding expenses.",
        "descriptionPlaceholder": "e.g. grocery trip, salary, or cash transfer",
        "feature.expenseTitle": "Expense Tracking",
        "feature.expenseDesc": "Record where your money goes with just a few clicks.",
        "feature.expenseDetails": "Easily log every expense with a single tap and categorize your spending. Get a full picture of your cash flow with monthly breakdowns.",

        "feature.graphsTitle": "Interactive Graphs",
        "feature.graphsDesc": "Visualize your monthly spending and savings patterns.",
        "feature.graphsDetails": "Beautiful, dynamic charts help you quickly understand trends in your income and spending, empowering smarter financial decisions.",

        "feature.syncTitle": "Secure Sync",
        "feature.syncDesc": "Keep your data safe across all your devices.",
        "feature.syncDetails": "Data is stored securely in the cloud with 2FA support. Access your budget from your phone, tablet, or desktop seamlessly.",

        "feature.aiTitle": "AI Notifications",
        "feature.aiDesc": "Get alerts when you’re close to overspending.",
        "feature.aiDetails": "Smart alerts notify you of risky patterns in your spending and recommend better ways to stick to your budget.",

        "feature.sharedTitle": "Shared Accounts",
        "feature.sharedDesc": "Budget together with your partner or family.",
        "feature.sharedDetails": "Invite others to manage finances together — perfect for couples, roommates, or families aiming for common financial goals.",
        "sharedView": "Shared View",
"myView": "My View",
"account.sendInvite": "Send Invite",
"account.edit": "Edit",
"edit": "Edit",
"sendInvite": "Send Invite",
"budgetsTitle": "Budgets",
"overBudget": "🚨 Over budget!",
"percentUsed": "⚠️ Used",
"addBudgetButton": "➕ Add Budget",
"selectCategory": "-- Select Category --",
"limit": "Limit",
"updateBudget": "Update Budget",
"submitBudget": "Add Budget",
"fillAllFields": "Fill all fields",
"confirmDeleteBudget": "Delete budget for",
"deletedBudget": "Deleted",
"deleteBudgetFailed": "Failed to delete budget",
"saveFailed": "Save failed"










    },
    sl: {
        balance: 'Stanje',
        income: 'Prihodek',
        expense: 'Strošek',
        cash: 'Gotovina',
        card: 'Kartica',
        add: 'Dodaj',
        cancel: 'Prekliči',
        addTransaction: 'Dodaj transakcijo',
        method: 'Način',
        amount: 'Znesek',
        category: 'Kategorija',
        type: 'Tip',
        salary: 'Plača',
        donation: 'Donacija',
        other: 'Drugo',
        transactionHistory: 'Zgodovina transakcij',
        close: 'Zapri',
        settings: 'Nastavitve',
        language: 'Jezik',
        currency: 'Valuta',
        erase: 'Izbriši vse transakcije',
        privacy: 'Politika zasebnosti',
        terms: 'Pogoji uporabe',
        userNotLoggedIn: "Uporabnik ni prijavljen",
        transactionAdded: "Transakcija dodana!",
        errorSaving: "Napaka pri shranjevanju.",
        choose: "Izberi",
        source: "Vir",
        scholarship: "Štipendija",
        deleteAll: "Izbriši vse transakcije",
        deleteAllConfirm: "Ali ste prepričani, da želite izbrisati vse transakcije?",
        deleteAllSuccess: "Vse transakcije so izbrisane.",
        deleteAllError: "Napaka pri brisanju transakcij.",
        deleteAllWarning: "To dejanje je nepovratno. Ste prepričani?",
        deleteAllWarningTitle: "Opozorilo",
        deleteAllWarningMessage: "To dejanje je nepovratno. Ste prepričani, da želite izbrisati vse transakcije?",
        deleteAllWarningConfirm: "Da, izbriši vse",
        deleteAllWarningCancel: "Prekliči",
        deleteAllWarningSuccess: "Vse transakcije so izbrisane.",
        deleteAllWarningError: "Napaka pri brisanju transakcij.",
        groceries: "Živila",
        home: "Dom",
        "eating out": "Jesti zunaj",
        "food delivery": "Dostava hrane",
        coffee: "Kava",
        car: "Avto",
        health: "Zdravje",
        sport: "Šport",
        subscriptions: "Naročnine",
        tech: "Tehnologija",
        entertainment: "Zabava",
        personal: "Osebno",
        clothing: "Oblačila",
        gifts: "Darila",
        education: "Izobraževanje",
        business: "Posel",
        charity: "Dobrodelnost",
        pets: "Hišni ljubljenčki",
        confirmErase: "Ali ste prepričani?",
        eraseSuccess: "Vse transakcije so bile izbrisane.",
        yes: "Da",
        ok: "V redu",
        export: 'Izvoz',
        exportCSV: 'Izvozi CSV',
        exportPDF: 'Izvozi PDF',
        importCSV: 'Uvozi CSV (trenutni mesec)',
        data: 'Podatki',
        settingsTitle: 'Nastavitve',
        noUser: 'Uporabnik ni prijavljen',
        importSuccess: 'Uvoz uspešen ',
        exportSuccess: 'Izvoz uspešen ',
        confirm: 'Potrdi',
        date: 'Datum',
        description: 'Opis',
        tour_account_toggle: '👥 Preklopite med "Mojim pogledom" (vaši podatki) in "Skupnim pogledom" (vključno s transakcijami povezanih uporabnikov).',
        tour_balance_section: '💰 To je vaše skupno razpoložljivo stanje, razdeljeno med Gotovino in Kartico.',
        tour_advice_button: '🤖 Potrebujete pomoč pri varčevanju? Vprašajte našega pametnega asistenta za osebni nasvet!',
        tour_fab: '☰ Tapnite tukaj za dostop do nastavitev (⚙️), izbiro meseca (📅) ali hitro dodajanje nove transakcije (+).',
        budgetOverrunTitle: 'Prekoračitev proračuna:',
        dismissClick: 'Kliknite kjerkoli za zaprtje',
        totalBalance: 'Skupno stanje',
        spendingOverview: 'Pregled porabe',
        expensesByCategory: 'Stroški po kategorijah',
        viewReports: 'Poglej celotno poročilo',
        latestTransactions: 'Zadnje transakcije',
        seeAll: 'Poglej vse',
        today: 'Danes',
        yesterday: 'Včeraj',
        sharedUser: 'Skupni uporabnik',
        assistantMessage: 'Hej! Tukaj sem, da pomagam!',
        "about.andonijaIntro": "Sem Andonija 👋",
        "about.intro1": "Študiram informacijske in podatkovne tehnologije na FERI Maribor, kjer se učim razvijati uporabne, varne in uporabniku prijazne spletne strani.",
        "about.intro2": "Spendly se je začel kot šolski projekt — zdaj je platforma, ki spodbuja premišljene navade pri ravnanju z denarjem. Z enostavnim vnosom, čistim izgledom in opcijskimi AI-funkcijami ti Spendly pomaga zavestno upravljati vsak strošek.",

        "about.missionTitle": "Naše poslanstvo",
        "about.mission1": "Spendly je vaš osebni pomočnik za finance, zasnovan za enostavno, sodelovalno in prijetno načrtovanje proračuna.",
        "about.mission2": "V svetu, kjer večina aplikacij skriva bistvene funkcije za naročninami, prijavami v banko ali zapletenimi vmesniki, Spendly izbere drugačno pot.",
        "about.mission3": "Ne glede na to, ali upravljate lastne finance, varčujete kot par ali zbirate za nekaj večjega — Spendly se prilagaja vašemu življenju, ne obratno.",

        "about.banner": "🎉 BREZPLAČNO! Brez naročnin. Brez omejitev. Spendly vam pomaga ohraniti nadzor nad financami — ker nam je mar. 💛",

        "about.whySpendly": "Zakaj Spendly",
        "about.value1Title": "Enostavnost",
        "about.value1Text": "Ročno sledenje brez zapletov.",
        "about.value2Title": "Zasebnost",
        "about.value2Text": "Brez povezav z bankami, popoln nadzor.",
        "about.value3Title": "Transparentnost",
        "about.value3Text": "Zasnovano s strani študentke, za vsakogar.",
        "about.value4Title": "Jasnost",
        "about.value4Text": "Jasni grafi in vizualizacije, ki imajo smisel.",
        "about.value5Title": "Brezplačno",
        "about.value5Text": "Ni več stroškov za naročnine!",

        "about.ctaTitle": "Pridruži se gibanju",
        "about.ctaText": "Spendly ti ponuja vse, kar potrebuješ za obvladovanje proračuna —",
        "about.ctaStrong": "popolnoma brezplačno",
        "about.ctaButton": "Ustvari brezplačen račun",
        "account.myAccount": "Moj račun",
        "account.personalDetails": "Osebni podatki",
        "account.fullName": "Polno ime",
        "account.profilePhoto": "Profilna slika",
        "account.twofaTitle": "Dvofaktorska avtentikacija",
        "account.twofaEnabled": "✅ 2FA je omogočen na vašem računu.",
        "account.phonePlaceholder": "Telefonska številka (npr. +386...)",
        "account.sendCode": "Pošlji kodo",
        "account.enterCode": "Vnesi kodo",
        "account.verifyEnable": "Preveri in omogoči",
        "account.collaborateTitle": "Sodeluj",
        "account.collabDescription": "Želite spremljati finance s partnerjem, prijateljem ali družinskim članom? Vnesite njihov e-poštni naslov spodaj za povabilo. Ko sprejmejo, boste oba videla isti proračun in transakcije v realnem času.",
        "account.emailPlaceholder": "npr. partner@email.com",
        "account.deleteAccount": "Izbriši moj račun",
        spendSmarter: "Pametneje trošite s Spendly!",
        discoverFeatures: "Odkrijte funkcije, ki vam pomagajo prevzeti nadzor nad osebnimi financami.",
        funFact: "Zanimivost",
        didYouKnow: "Ali ste vedeli?",
        statFact: "Ljudje, ki spremljajo stroške, prihranijo do",
        statMonth: "več na mesec!",
        saveSmarter: "Ste pripravljeni varčevati pametneje?",
        createAccount: "Ustvari račun",
        heroTitle: "Pametnejši način upravljanja z denarjem",
        heroSubtitle: "Spendly vam pomaga slediti vsakemu strošku...",
        getStarted: "Začni zdaj",
        greeting: "Živjo",
        greetingMessage: "Upam, da imaš lep dan! ☀️",
        videoNotSupported: "Vaš brskalnik ne podpira video oznake.",
        privacyPolicyTitle: "Politika zasebnosti",
        lastUpdated: "Zadnja posodobitev: 26. maj 2025",
        privacyIntro: "V",
        privacyIntroCont: " podjetju Spendly nam je vaša zasebnost pomembna. Ta politika zasebnosti pojasnjuje, kako zbiramo, uporabljamo in varujemo vaše osebne podatke.",
        section1Title: "1. Katere podatke zbiramo",
        infoEmailName: "E-pošta in ime ob registraciji",
        infoPhone: "Neobvezna telefonska številka za 2FA",
        infoFinancialData: "Finančni podatki, ki jih vnesete (transakcije, proračuni)",
        infoBrowserData: "Podatki o brskalniku/napravi za izboljšanje aplikacije",
        section2Title: "2. Kako uporabljamo vaše podatke",
        usePersonalizedFeatures: "Za zagotavljanje prilagojenih finančnih funkcij",
        use2FA: "Za zaščito vašega računa preko 2FA",
        useAnalytics: "Za analizo uporabe in izboljšanje uporabniške izkušnje",
        section3Title: "3. Varnost podatkov",
        dataSecurity: "Uporabljamo Firebase Authentication in Firestore s šifriranimi povezavami. Vaših podatkov ne delimo s tretjimi osebami brez vašega soglasja.",
        section4Title: "4. Vaše pravice",
        yourRights: "Kadar koli lahko zahtevate vpogled, spremembo ali izbris svojih podatkov.",
        section5Title: "5. Spremembe",
        changesNotice: "Ta politika se lahko spremeni. O pomembnih posodobitvah boste obveščeni.",
        reportsTitle: '📊 Finančna poročila',
        filterBy: 'Filtriraj po:',
        filterAll: 'Celotno obdobje',
        filterDay: 'Dan',
        filterWeek: 'Teden',
        filterMonth: 'Mesec',
        filterYear: 'Leto',
        filterRange: 'Obseg po meri',
        selectYear: 'Izberi leto',
        chartDailyLabel: 'Dnevni stroški (€)',
        chartDailyTitle: 'Dnevni trendi porabe (€)',
        chartXAxisDate: 'Datum',
        chartYAxisAmount: 'Znesek',
        chartBarTitle: 'Mesečni prihodki in izdatki (€)',
        chartIncome: 'Prihodki',
        chartExpense: 'Stroški',
        chartXAxisMonth: 'Mesec',
        chartPieTitle: 'Stroški po kategorijah',
        noCategoryData: 'Ni razpoložljivih kategorij stroškov.',
        chartDoughnutTitle: 'Poraba: Kartica proti gotovini',
        onlyOneMethod: 'V tem filtru je bila uporabljena samo ena plačilna metoda.',
        chartBalanceLabel: 'Stanje (€)',
        chartBalanceTitle: 'Vaše stanje skozi čas',
        chartYAxisBalance: 'Stanje (€)',
        tooltipDate: 'Datum',
        tooltipBalance: 'Stanje',
        termsTitle: 'Pogoji uporabe',
        termsEffectiveDate: 'Datum začetka veljavnosti',
        termsAcceptance: '1. Sprejem pogojev',
        termsAcceptanceText: 'Z uporabo Spendlyja se strinjate s temi pogoji uporabe. Če se ne strinjate, prenehajte uporabljati aplikacijo.',
        termsUse: '2. Uporaba storitve',
        termsUseText: 'Spendly je aplikacija za sledenje osebnih financ, namenjena osebam starejšim od 16 let. Strinjate se, da ne boste zlorabljali storitve ali dostopali do podatkov drugih oseb.',
        termsSecurity: '3. Račun in varnost',
        termsSecurityText: 'Odgovorni ste za varnost svojih prijavnih podatkov. Za dodatno zaščito priporočamo uporabo dvostopenjske avtentikacije (2FA).',
        termsPrivacy: '4. Podatki in zasebnost',
        termsPrivacyText: 'Vaši finančni podatki so varno shranjeni v oblaku Firebase. Vaših podatkov ne prodajamo in jih ne delimo s tretjimi osebami.',
        termsLimitations: '5. Omejitve',
        termsLimitationsText: 'Spendly se ne povezuje z bančnimi API-ji in ne nudi računovodskih, davčnih ali pravnih nasvetov. Vse podatke morate vnesti ročno.',
        termsAI: '6. Nasveti umetne inteligence',
        termsAIText: 'Nasveti, ki jih poda umetna inteligenca, so zgolj informativni in ne predstavljajo finančnega svetovanja.',
        termsTermination: '7. Prenehanje uporabe',
        termsTerminationText: 'Pridržujemo si pravico do prekinitve ali izbrisa računa, ki krši te pogoje.',
        termsChanges: '8. Spremembe',
        termsChangesText: 'Ti pogoji se lahko občasno spremenijo. Nadaljnja uporaba aplikacije pomeni, da se strinjate s spremenjenimi pogoji.',
        termsContact: '9. Kontakt',
        termsContactText: 'Če imate vprašanja, nas kontaktirajte na: andonija.todorova@student.um.si',
        sharedBy: 'Delil uporabnik',
        anotherUser: 'Drug uporabnik',
        "direction": "Smer prenosa",
        "cardToCash": "Kartica → Gotovina",
        "cashToCard": "Gotovina → Kartica",

        "optional": "neobvezno",
        "invalidAmount": "🚨 Vnesi veljaven znesek, večji od 0.",
        "notEnoughCash": "🚨 Premalo sredstev! Ni dovolj gotovine.",
        "notEnoughCard": "🚨 Premalo sredstev! Ni dovolj na kartici.",
        "transferNotEnoughCash": "🚨 Prenos ni možen. Premalo gotovine.",
        "transferNotEnoughCard": "🚨 Prenos ni možen. Premalo sredstev na kartici.",
        "resetPassword": "Ponastavi geslo",
        "yourEmail": "Tvoj e-naslov",
        "sendResetLink": "Pošlji povezavo za ponastavitev",
        "resetLinkSent": "Povezava za ponastavitev poslana. Preveri svoj e-nabiralnik.",
        "resetFailed": "Pošiljanje povezave ni uspelo.",
        "emailSent": "E-pošta poslana. Preveri svoj e-nabiralnik.",
        "backToLogin": "Nazaj na prijavo",
        "login": "Prijava",
        "password": "Geslo",
        "email": "E-pošta",
        "loggingIn": "Prijavljanje…",
        "or": "ali",
        "continueGoogle": "Nadaljuj z Googlom",
        "forgotPassword": "Ste pozabili geslo?",
        "reset": "Ponastavi",
        "noAccount": "Nimate računa?",
        "signUp": "Registriraj se",
        "enterCode": "Vnesi SMS kodo",
        "verify": "Potrdi kodo",
        "emailNotVerified": "E-pošta ni potrjena. Preverite svoj poštni nabiralnik.",
        "emailNotVerifiedGoogle": "Googlov račun ni potrjen. Potrdite e-pošto.",
        "smsFailed": "Pošiljanje SMS kode ni uspelo.",
        "networkIssue": "Težave z omrežjem. Poskus ponovitve...",
        "errorWrongPassword": "Napačen e-poštni naslov ali geslo.",
        "errorUserNotFound": "Uporabnik s tem e-poštnim naslovom ne obstaja.",
        "errorTooManyRequests": "Preveč poskusov. Poskusite kasneje.",
        "errorInvalidEmail": "Neveljavna oblika e-pošte.",
        "errorInternal": "Prišlo je do notranje napake. Poskusite znova.",
        "errorLoginFailed": "Prijava ni uspela. Preverite podatke.",
        "popupBlocked": "Pojavno okno blokirano. Preusmeritev na prijavo...",
        "errorAccountExists": "Račun s tem e-poštnim naslovom že obstaja z drugo metodo prijave.",
        "errorGoogleInvalid": "Neveljavni Googlov podatki za prijavo.",
        "errorGoogleGeneric": "Prijava z Googlom ni uspela.",
        "verificationSuccess": "Verifikacija uspešna.",
        "smsInvalid": "Neveljavna koda. Poskusite znova.",
        "hi": "Živjo",
        "there": "tam",
        "niceToMeet": "Lepo te je spoznati!",
        "homePageTitle": "Domov",
        "whyJoinSpendly": "Zakaj izbrati Spendly?",
        "overviewAtGlance": "Pregled dashboarda na prvi pogled",
        "overviewText": "V trenutku poglejte finančno stanje z jasnimi in lepimi prikazi.",
        "smartBudgetTracking": "Pametno sledenje proračunu",
        "budgetText": "Nikoli več ne presezite porabe z intuitivnim sledenjem proračuna.",
        "categorizeExpenses": "Kategorizacija stroškov",
        "categorizeText": "Enostavno razvrstite svoje stroške v kategorije.",
        "detailedAnalytics": "Podrobna analitika",
        "analyticsText": "Spoznajte svoje potrošniške navade z uporabnimi analitičnimi podatki.",
        "fullHistory": "Celotna zgodovina transakcij",
        "historyText": "Vaša celotna finančna zgodovina, lepo prikazana.",
        "multiDevice": "Podpora za več naprav",
        "multiDeviceText": "Enostavno sinhronizirajte svoj proračun na vseh napravah.",

        "fact1": "Ljudje, ki spremljajo stroške, prihranijo do 20 % več na mesec!",
        "fact2": "Proračun zmanjšuje impulzivne nakupe za 25 %.",
        "fact3": "Pari, ki delijo proračun, se prepirajo 30 % manj o denarju.",
        "fact4": "Redno tedensko preverjanje proračuna poveča konsistentnost varčevanja.",
        "fact5": "Zavedanje o porabi poveča finančno samozavest že v 2 tednih.",
        "fact6": "Spremljanje denarnega toka razkrije skrite naročnine.",
        "fact7": "Uporabniki proračunov 2x pogosteje dosežejo varčevalne cilje.",
        "fact8": "Mladi odrasli z aplikacijami za proračun prihranijo 15 % več letno.",
        "fact9": "Največ prekomerne porabe se zgodi v zadnjih 5 dneh v mesecu.",
        "fact10": "Vizualni grafi povečajo zapomnitev proračuna za 70 %.",
        "account.currentlySharing": "Trenutno si delite podatke z",
        "account.stopCollaborating": "Prekini sodelovanje",
        "fullName": "Polno ime",
        "termsConfirm": "Prebral/-a sem in sprejemam ",
        "termsOfService": "Pogoje uporabe",
        "and": "in",
        "privacyPolicy": "Politiko zasebnosti",
        "continueWithGoogle": "Nadaljuj z Googlom",
        "alreadyHaveAccount": "Že imate račun?",
        "signIn": "Prijava",
        "acceptTerms": "Prosimo, da sprejmete pogoje uporabe in politiko zasebnosti.",
        "verificationSent": "Potrditveno e-poštno sporočilo je bilo poslano. Preverite svoj nabiralnik.",
        "emailInUse": "Račun s tem e-poštnim naslovom že obstaja.",
        "invalidEmail": "Neveljaven e-poštni naslov.",
        "weakPassword": "Geslo mora imeti vsaj 6 znakov.",
        "signupFailed": "Prišlo je do napake. Poskusite znova.",
        "googleSignupFailed": "Registracija z Googlom ni uspela.",
        "noIncomeYet": "🚫 Najprej vnesite prihodek, preden dodate strošek.",
        "descriptionPlaceholder": "npr. nakup živil, plača ali prenos gotovine",
        "feature.expenseTitle": "Sledenje stroškom",
        "feature.expenseDesc": "Zabeležite, kam gre vaš denar, z nekaj kliki.",
        "feature.expenseDetails": "Enostavno zabeležite vsak strošek in ga kategorizirajte. Pridobite popoln pregled nad denarnim tokom z mesečnimi analizami.",

        "feature.graphsTitle": "Interaktivni grafi",
        "feature.graphsDesc": "Vizualizirajte svojo mesečno porabo in varčevanje.",
        "feature.graphsDetails": "Lepi in dinamični grafi pomagajo razumeti trende in sprejemati pametnejše finančne odločitve.",

        "feature.syncTitle": "Varna sinhronizacija",
        "feature.syncDesc": "Ohranite varnost podatkov na vseh napravah.",
        "feature.syncDetails": "Podatki so varno shranjeni v oblaku z 2FA zaščito. Do proračuna dostopajte s telefona, tablice ali računalnika.",

        "feature.aiTitle": "AI obvestila",
        "feature.aiDesc": "Prejmite opozorila, ko ste blizu prekoračitve.",
        "feature.aiDetails": "Pametna obvestila vas opozorijo na tveganje pri porabi in priporočajo boljše proračunske navade.",

        "feature.sharedTitle": "Skupni računi",
        "feature.sharedDesc": "Načrtujte proračun skupaj s partnerjem ali družino.",
        "feature.sharedDetails": "Povabite druge k skupnemu upravljanju financ — popolno za pare, sostanovalce ali družine z istimi cilji.",
        "sharedView": "Skupni pogled",
"personalView": "Moj pogled",
"account.sendInvite": "Pošlji povabilo",
"account.edit": "Uredi",
"edit": "Uredi",
"sendInvite": "Pošlji povabilo",
"budgetsTitle": "Proračuni",
"overBudget": "🚨 Prekoračen proračun!",
"percentUsed": "⚠️ Porabljeno",
"addBudgetButton": "➕ Dodaj proračun",
"selectCategory": "-- Izberite kategorijo --",
"limit": "Omejitev",
"updateBudget": "Posodobi proračun",
"submitBudget": "Dodaj proračun",
"fillAllFields": "Izpolnite vsa polja",
"confirmDeleteBudget": "Izbrišem proračun za",
"deletedBudget": "Izbrisan",
"deleteBudgetFailed": "Brisanje proračuna ni uspelo",
"saveFailed": "Shranjevanje ni uspelo"


    }
};

const LanguageContext = createContext<LangContextType>({
    language: 'en',
    setLanguage: () => { },
    t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');
    const t = (key: string) => translations[language][key] || key;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}
